class CfgPatches
{
	class DinkyWalker
	{
		units[] = 
		{
			 Clothing
		 Clothing_Base
		 TaloonBag_ColorBase 
		 TortillaBag 
		 CourierBag 
		 FurCourierBag 
		 ImprovisedBag 
		 FurImprovisedBag 
		 DryBag_ColorBase 
		 HuntingBag 
		 MountainBag_ColorBase 
		 SmershBag 
		 ChildBag_ColorBase 
		 GhillieBushrag_ColorBase 
		 GhillieTop_ColorBase 
		 GhillieSuit_ColorBase 
		 LeatherSack_ColorBase 
		 AssaultBag_ColorBase 
		 CoyoteBag_ColorBase 
		 AliceBag_ColorBase 
		 LeatherBelt_ColorBase 
		 SportGlasses_ColorBase 
		 AviatorGlasses 
		 DesignerGlasses 
		 ThickFramesGlasses 
		 ThinFramesGlasses 
		 TacticalGoggles 
		 NVGHeadstrap 
		 WorkingGloves_ColorBase 
		 TacticalGloves_ColorBase 
		 NBCGloves_ColorBase 
		 SurgicalGloves_ColorBase 
		 LeatherGloves_ColorBase 
		 OMNOGloves_ColorBase 
		 BallisticHelmet_ColorBase 
		 BaseballCap_ColorBase 
		 ZSh3PilotHelmet 
		 ConstructionHelmet_ColorBase 
		 BurlapSackCover 
		 BeanieHat_ColorBase 
		 Ushanka_ColorBase 
		 PumpkinHelmet 
		 MotoHelmet_ColorBase 
		 DarkMotoHelmet_ColorBase 
		 BandanaHead_ColorBase 
		 RadarCap_ColorBase 
		 MilitaryBeret_ColorBase 
		 FlatCap_ColorBase 
		 ZmijovkaCap_ColorBase 
		 CowboyHat_ColorBase 
		 BoonieHat_ColorBase 
		 OfficerHat 
		 PoliceCap 
		 PilotkaCap 
		 TankerHelmet 
		 GorkaHelmet 
		 FirefightersHelmet_ColorBase 
		 SkateHelmet_ColorBase 
		 WeldingMask 
		 PrisonerCap 
		 GhillieHood_ColorBase 
		 LeatherHat_ColorBase 
		 MedicalScrubsHat_ColorBase 
		 GreatHelm 
		 Ssh68Helmet 
		 DirtBikeHelmet_ColorBase 
		 DirtBikeHelmet_Visor 
		 DirtBikeHelmet_Mouthguard 
		 NBCHoodBase 
		 HockeyHelmet_ColorBase 
		 SantasHat 
		 Mich201Helmet 
		 Mich2001Helmet 
		 Universal_Bandana_Redpattern Base_
		 GasMask 
		 BandanaMask_ColorBase 
		 NioshFaceMask 
		 BalaclavaMask_ColorBase 
		 GP5GasMask 
		 Balaclava3Holes_ColorBase 
		 SantasBeard 
		 MouthRag 
		 SurgicalMask 
		 HockeyMask 
		 Jeans_ColorBase 
		 CargoPants_ColorBase 
		 TTSKOPants 
		 HunterPants_ColorBase 
		 CanvasPants_ColorBase 
		 CanvasPantsMidi_ColorBase 
		 TrackSuitPants_ColorBase 
		 GorkaPants_ColorBase 
		 PolicePants 
		 PolicePantsOrel 
		 ParamedicPants_ColorBase 
		 FirefightersPants_ColorBase 
		 PrisonUniformPants 
		 LeatherPants_ColorBase 
		 MedicalScrubsPants_ColorBase 
		 USMCPants_ColorBase 
		 SlacksPants_ColorBase 
		 BDUPants 
		 NBCPantsBase 
		 Breeches_ColorBase 
		 ShortJeans_ColorBase 
		 Skirt_ColorBase 
		 JumpsuitPants_ColorBase 
		 AthleticShoes_ColorBase 
		 HikingBoots_ColorBase 
		 HikingBootsLow_ColorBase 
		 Wellies_ColorBase 
		 WorkingBoots_ColorBase 
		 JungleBoots_ColorBase 
		 DressShoes_ColorBase 
		 MilitaryBoots_ColorBase 
		 CombatBoots_ColorBase 
		 JoggingShoes_ColorBase 
		 LeatherShoes_ColorBase 
		 Sneakers_ColorBase 
		 NBCBootsBase 
		 Ballerinas_ColorBase 
		 TTSKOBoots 
		 Armband_ColorBase 
		 Sweater_ColorBase 
		 Shirt_ColorBase 
		 TShirt_ColorBase 
		 Hoodie_ColorBase 
		 TacticalShirt_ColorBase 
		 HikingJacket_ColorBase 
		 Raincoat_ColorBase 
		 M65Jacket_ColorBase 
		 TTsKOJacket_ColorBase 
		 GorkaEJacket_ColorBase 
		 RidersJacket_ColorBase 
		 WoolCoat_ColorBase 
		 TrackSuitJacket_ColorBase 
		 PoliceJacket 
		 PoliceJacketOrel 
		 ParamedicJacket_ColorBase 
		 FirefighterJacket_ColorBase 
		 PrisonUniformJacket 
		 MiniDress_ColorBase 
		 QuiltedJacket_ColorBase 
		 BomberJacket_ColorBase 
		 LeatherJacket_ColorBase 
		 HuntingJacket_ColorBase 
		 MedicalScrubsShirt_ColorBase 
		 LabCoat 
		 NurseDress_ColorBase 
		 USMCJacket_ColorBase 
		 Blouse_ColorBase 
		 NBCJacketBase 
		 DenimJacket 
		 TelnyashkaShirt 
		 ChernarusSportShirt 
		 JumpsuitJacket_ColorBase 
		 BDUJacket 
		 ManSuit_ColorBase 
		 WomanSuit_ColorBase 
		 LeatherShirt_ColorBase 
		 PlateCarrierVest 
		 SmershVest 
		 PressVest_ColorBase 
		 UKAssVest_ColorBase 
		 PoliceVest 
		 PlateCarrierHolster 
		 ChestHolster 
		 HighCapacityVest_ColorBase 
		 LeatherStorageVest_ColorBase 
		 HuntingVest 
		 ReflexVest 
		 Headtorch_ColorBase 
		 Switchable_Base
 
		};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Characters","DZ_Characters_Zombies"};
	};
};
class CfgVehicles
{
	class DZ_LightAI;
	class DayZInfected: DZ_LightAI{};
	class ZombieBase: DayZInfected
	{
		class Cargo
		{
			itemsCargoSize[] = {4,5};
			allowOwnedCargoManipulation = 1;
			openable = 0;
		};
	};
};